# Niveles para la categoría de tipo de viaje

level_l <- c("3","4","5","6","7","8","9","12","14","15","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","999")


# Niveles días de la semana
level_w <- c('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')

#NivelesDepartment
level_d<-c('1-HR PHOTO','ACCESSORIES','AUTOMOTIVE','BAKERY','BATH AND SHOWER','BEAUTY','BEDDING','BOOKS AND MAGAZINES','BOYS WEAR','BRAS & SHAPEWEAR','CAMERAS AND SUPPLIES','CANDY, TOBACCO, COOKIES','CELEBRATION','COMM BREAD','CONCEPT STORES','COOK AND DINE','DAIRY','DSD GROCERY','ELECTRONICS','FABRICS AND CRAFTS','FINANCIAL SERVICES','FROZEN FOODS','FURNITURE','GIRLS WEAR, 4-6X  AND 7-14','GROCERY DRY GOODS','HARDWARE','HEALTH AND BEAUTY AIDS','HOME DECOR','HOME MANAGEMENT','HORTICULTURE AND ACCESS','HOUSEHOLD CHEMICALS/SUPP','HOUSEHOLD PAPER GOODS','IMPULSE MERCHANDISE','INFANT APPAREL','INFANT CONSUMABLE HARDLINES','JEWELRY AND SUNGLASSES','LADIES SOCKS','LADIESWEAR','LARGE HOUSEHOLD GOODS','LAWN AND GARDEN','LIQUOR,WINE,BEER','MEAT - FRESH & FROZEN','MEDIA AND GAMING','MENS WEAR','OFFICE SUPPLIES','OPTICAL - FRAMES','OPTICAL - LENSES','OTHER DEPARTMENTS','PAINT AND ACCESSORIES','PERSONAL CARE','PETS AND SUPPLIES','PHARMACY OTC','PHARMACY RX','PLAYERS AND ELECTRONICS','PLUS AND MATERNITY','PRE PACKED DELI','PRODUCE','SEAFOOD','SEASONAL','SERVICE DELI','SHEER HOSIERY','SHOES','SLEEPWEAR/FOUNDATIONS','SPORTING GOODS','SWIMWEAR/OUTERWEAR','TOYS','WIRELESS')

